M48
; DRILL file KiCad 10.0.1 date 2026-06-28T11:47:56
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-28T11:47:56+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X189.428Y-47.605
X195.208Y-47.605
T2
X134.0Y-44.5
X134.0Y-85.0
X204.0Y-44.5
X204.0Y-85.0
M30
